### ISSUE TITLE
Incoherence

### ISSUE THREAD

**Issue by drupol** [markwilson/array-subsets#1]
Hi,

The generate() method does not generate any permutation.

Why ?

According to what you wrote, [1,2,3,4,5] is the same as [5,4,3,2,1]. The order of elements matters when it comes to permutations.

**Comment by markwilson** [comment]
The generate method is for generating the an instance of a Generator. Agreed this naming probably needs improving.

The order isn't affected when generating the permutations, if the input is [5, 4, 3, 2, 1] the output will be different to using [1, 2, 3, 4, 5].

Can you give me an example of how you're trying to use it currently?

**Comment by drupol** [comment]
Hi @markwilson,

Let's say we use this dataset: `$dataset = [1, 2, 3, 4];`

For me, the definition of permutations should take care of the order of each elements, so, if we want to generate the permutations of size 4 of this dataset, it should return:

```
[1, 2, 3, 4]
[1, 2, 4, 3]
[1, 3, 2, 4]
[1, 3, 4, 2]
[1, 4, 2, 3]
[1, 4, 3, 2]
[2, 1, 4, 3]
[2, 1, 3, 4]
[2, 3, 4, 1]
[2, 3, 1, 4]
[2, 4, 3, 1]
[2, 4, 1, 3]
[3, 1, 2, 4]
[3, 1, 4, 2]
[3, 2, 1, 4]
[3, 2, 4, 1]
[3, 4, 1, 2]
[3, 4, 2, 1]
[4, 1, 3, 2]
[4, 1, 2, 3]
[4, 2, 3, 1]
[4, 2, 1, 3]
[4, 3, 2, 1]
[4, 3, 1, 2]
```

Let me know what you think.

**Comment by markwilson** [comment]
Thanks for the feedback. That makes sense, I'll look at updating this to reflect that change. It was only supposed to provide the possible subsets of the original array, maybe it shouldn't be called "permutations" in its current state.

**Comment by drupol** [comment]
I'm struggling since a couple of days, trying to do it using yield so I spare as much memory, but I still haven't found a valid solution.
Don't forget that the dataset could be composed of integers or any other PHP objects.

**Comment by markwilson** [comment]
@drupol - I've now renamed this to be more relevant and there is a separate array-permutations repository to handle the scenario you described.

**Comment by drupol** [comment]
Thanks @markwilson ! Nice one.

I've integrated your changes in my project: https://github.com/drupol/phpermutations
